#!/usr/bin/bash -e

data_basedir={{ data_basedir }}

debug=
if [ -n "$DEBUG" ] ; then
    debug=echo
fi

instance="$1"

if [ -z "$instance" ] ; then
    echo "Instance must be specified as the first parameter." >&2
    echo "The second parameter may be the base instance to copy data from.." >&2
    ls -la "$data_basedir"
    exit 64
fi

if ! test -d "$data_basedir"/"$instance"-green ; then
    echo "Instance $instance does not exist in $data_basedir" >&2
    ls -la "$data_basedir"
    exit 2
fi

base="$2"
if [ -z "$base" ] ; then
    base=master
fi

if ! test -d "$data_basedir"/"$base"-green ; then
    echo "Instance $base does not exist in $data_basedir" >&2
    ls -la "$data_basedir"
    exit 2
fi

$debug service container-plone-"$instance"-green stop || true
$debug cd "$data_basedir"
$debug rm -rf "$instance"-green/blobstorage "$instance"-green/filestorage
$debug cp -al "$base"-green/blobstorage "$instance"-green/blobstorage
$debug cp -a "$base"-green/filestorage "$instance"-green/filestorage
$debug service container-plone-"$instance"-green start
