#!/usr/bin/python3

import time

import contextlib
import os
import sys
import subprocess
import time


def unescape(escaped):
    return escaped.replace("\\", "\\\\")


@contextlib.contextmanager
def atomic_outputter(filename):
    if filename.startswith("/dev") or filename == "-" or os.path.islink(filename):
        if filename == "-":
            filename = "/dev/stdout"
        tmpf, finalf = filename, filename
    else:
        if not os.path.sep in filename:
            cmd = "cat /proc/$(pgrep -f ^/usr/bin/.*node.*exporter | head -1)/cmdline | tr '\\0' '\\n' | grep -- --collector.textfile.directory= | sed 's/^--collector.textfile.directory=//'"
            directory = subprocess.check_output(["bash", "-c", cmd], text=True).rstrip("\n")
            if not directory:
                print("Exiting because there is no node_exporter from which to infer the collector directory yet.", file=sys.stderr)
                sys.exit(0)
            filename = os.path.join(directory, filename)
        tmpf, finalf = filename + ".%s" % os.getpid(), filename
    with open(tmpf, "w") as out:
        try:
            yield out
            out.flush()
        except Exception:
            if tmpf != finalf:
                os.unlink(tmpf)
            raise
    if tmpf != finalf:
        if os.stat(tmpf).st_size == 0:
            os.unlink(tmpf)
        else:
            os.rename(tmpf, finalf)


def iter():
    in_ = subprocess.run(
        "systemctl show * -p Id,ActiveState,SubState".split(),
        capture_output=True,
        check=False,
        universal_newlines=True
    ).stdout

    class flushable(object):

        def __init__(self, out):
            self.out = out
            self.unit = {}
            self.flushed = False

        def unitadd(self, d):
            if len(d) != 2: return
            for src, dst in [
                ("Id", "service"),
                ("ActiveState", "state"),
                ("SubState", "substate"),
            ]:
                if d[0] == src:
                    d[0] = dst
            try:
                self.unit[d[0]] = d[1]
            except IndexError:
                assert 0, d

        def unitflush(self):
            if not self.unit: return
            if self.unit["service"].endswith(".device"):
                return
            if self.unit["service"].startswith("run-"):
                return
            if not self.flushed:
                print("# HELP systemd_unit_state Tracks the state of a systemd unit.", file=self.out)
                self.flushed = True
            self.out.write("systemd_unit_state{")
            self.out.write(",".join(
                k + "=" + '"' + unescape(v) + '"'
                for k, v in sorted(self.unit.items())
            ))
            self.out.write("} 1\n")
            self.unit.clear()


    with atomic_outputter(sys.argv[1]) as out:
        start = time.time()
        u = flushable(out)
        for line in in_.splitlines(True):
            if line != '\n':
                u.unitadd(line.strip().split("=", 1))
            else:
                u.unitflush()
        end = time.time()
        print("# HELP systemd_unit_state_collector_start_time_seconds Tracks the start of the collector run.", file=out)
        print("systemd_unit_state_collector_start_time_seconds %s" % start, file=out)
        print("# HELP systemd_unit_state_collector_end_time_seconds Tracks the end of the collector run.", file=out)
        print("systemd_unit_state_collector_end_time_seconds %s" % end, file=out)


while True:
    iter()
    time.sleep(5*60)
